-- Populate portfolio projects with actual data
INSERT INTO portfolio_projects (title, description, technologies, link, image_url, display_order) VALUES
  ('Policy Hub 1.0', 'A comprehensive ServiceNow-based policy management platform that centralizes over 400 enterprise policies across security, compliance, and operational domains. Features advanced categorization, search functionality, and automated compliance tracking with integrated document management workflows.', ARRAY['ServiceNow', 'Policy Management', 'Compliance Framework', 'Document Management', 'Security Operations'], '/portfolio', '/lovable-uploads/75ecce5a-4c43-44e1-9825-63545cfb5ab8.png', 1),
  
  ('Framework Fusion Engine', 'A community-driven cross-compliance framework mapping tool that streamlines compliance across multiple frameworks with AI-powered control mapping and gap analysis. Features comprehensive coverage of major compliance and security frameworks including NIST 800-53, PCI-DSS, and more.', ARRAY['Compliance Framework', 'AI-Powered Mapping', 'Security Standards', 'NIST', 'PCI-DSS', 'Gap Analysis'], 'https://mmacri.github.io/framework-fusion-engine/', '/lovable-uploads/e001dd85-f8b8-4c6e-9d04-e8b316bbebcb.png', 2),
  
  ('ServiceNow Solution Advisor Guide', 'An interactive assessment tool designed to help organizations evaluate their ServiceNow implementation readiness and identify optimal solution paths. Provides customized recommendations based on organizational maturity, technical requirements, and business objectives.', ARRAY['ServiceNow', 'Solution Architecture', 'Assessment Framework', 'JavaScript', 'Web Development'], 'https://mmacri.github.io/nowassess/index.html', '/lovable-uploads/a6fd2e82-34d4-4f60-90fc-4f5236a13aaf.png', 3),
  
  ('Customer Success Dashboard', 'Analytics dashboard that improved product adoption by 21% and increased NPS scores through better customer metrics tracking. Enabled data-driven decisions to improve customer satisfaction and identify growth opportunities.', ARRAY['PowerBI', 'Salesforce', 'Data Analytics', 'Customer Success'], 'https://mmacri.github.io/customer-engagement-tracker/', '/lovable-uploads/eb90f300-90d1-4c77-86ec-2814b17e1be4.png', 4),
  
  ('Strategic Partner Enablement', 'Partner program that delivered 644% revenue growth through improved partner enablement and streamlined workflows. Created technical training materials and solution demos that accelerated partner go-to-market activities.', ARRAY['Business Development', 'Partner Management', 'VMware', 'Cloud Services'], '/portfolio', NULL, 5),
  
  ('Security Compliance Framework', 'Developed a comprehensive security and compliance framework for enterprise customers that mapped to NIST, CIS, and other security standards to meet strict audit requirements.', ARRAY['NIST', 'CIS', 'Security Operations', 'Audit & Compliance'], '/portfolio', NULL, 6);